### ISSUE TITLE
Review Request: HowTo Render a Render Target

### ISSUE THREAD

**Issue by SimonDarksideJ** [MonoGame/docs.monogame.github.io#8]
### Description

To ensure everything is along the right lines as @dellis1972 and I go though the final reviews of the migrated XNA content, here is a sample of one of the first tutorials updated.

![image](https://github.com/MonoGame/monogame.github.io/assets/1793042/5e86603a-bc93-456e-b3b7-813f649f9fc9)

Comments Please.

**Comment by mrhelmut** [comment]
Maybe set the RenderTarget size to the texture size? (or whatever space you need to draw to) Because setting it to the backbuffer size might not be enough and will result in cropped drawing (and it might be misleading and make readers to assume that a render target has to be of the same size of the backbuffer)

Also, you don't need to cast the render target to Texture2D.

**Comment by SimonDarksideJ** [comment]
Added the changes.  Mainly needed feedback on the look and feel, but validating the content is also invaluable!
